language: node_js
node_js:
  - 12
addons:
  packages:
    - libgconf-2-4
script:
  - eslint 'src/**'
  - yarn test:coveralls
  - yarn test:cypress:ci
deploy:
  provider: heroku
  api_key: $HEROKU_API
  app: leonfoliveira-fordevs-react
  skip_cleanup: true
  on:
    branch: main
notifications:
  email: false
