language: node_js
node_js:
  - 12
script:
  - eslint 'src/**'
  - yarn test:coveralls
deploy:
  provider: heroku
  api_key: $HEROKU_API
  app: leonfoliveira-fordevs-react
  skip_cleanup: true
  on:
    branch: main
